name: clean-newlines
on: push
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Find and Replace
        uses: jacobtomlinson/gha-find-replace@v2
        with:
          find: "cupcake"
          replace: "BLOOD"
          include: "random/**"
          regex: false
