name: clean-newlines
on: push
jobs:
  clean-carriage-returns:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - run: |
          cat $GITHUB_WORKSPACE/random/*.txt
          for i in $GITHUB_WORKSPACE/random/*.txt; do sed $'s/cupcake/BLOOD/' $i > $i;done
          cat $GITHUB_WORKSPACE/random/*.txt
